[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["yolo_kiyoshi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
slack-sdk = "^3.33.4"
jupyterlab = "^4.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
